import React from 'react';
import Link from 'next/link';

export default function Terms() {
  return (
    <div className="container mx-auto px-4 py-12">
      <header className="mb-12 text-center">
        <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
        <p className="text-xl text-gray-300 max-w-3xl mx-auto">
          The rules and guidelines for using DreamBox
        </p>
      </header>

      <div className="max-w-4xl mx-auto card">
        <div className="prose prose-invert max-w-none">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using DreamBox services, including our TikTok account and website, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            DreamBox is an AI-powered service that transforms user-submitted dream descriptions into visual content, which is then posted to our TikTok account. The service includes:
          </p>
          <ul>
            <li>Collection of dream descriptions from TikTok comments</li>
            <li>AI-powered generation of videos based on dream descriptions</li>
            <li>Posting of generated videos to TikTok with attribution</li>
            <li>Management of a community centered around dream visualization</li>
          </ul>

          <h2>3. User Submissions</h2>
          <p>
            By submitting a dream description to DreamBox (via TikTok comments or other designated channels), you:
          </p>
          <ul>
            <li>Grant us permission to use your dream description to create visual content</li>
            <li>Grant us permission to share the resulting content on TikTok and other platforms</li>
            <li>Agree to have your username displayed as attribution (unless anonymity is requested)</li>
            <li>Affirm that your submission does not violate our content guidelines</li>
            <li>Understand that not all submissions will be selected for visualization</li>
          </ul>

          <h2>4. Content Guidelines</h2>
          <p>
            Dream submissions must not contain:
          </p>
          <ul>
            <li>Graphic violence or gore</li>
            <li>Explicit sexual content</li>
            <li>Hate speech or discriminatory content</li>
            <li>Personal identifying information</li>
            <li>Content that violates others' privacy</li>
            <li>Content that promotes illegal activities</li>
            <li>Content that infringes on intellectual property rights</li>
          </ul>
          <p>
            We reserve the right to reject or modify any submission that violates these guidelines.
          </p>

          <h2>5. Intellectual Property</h2>
          <p>
            You retain ownership of your original dream descriptions. By submitting content to DreamBox, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, adapt, publish, and display the content in connection with our services.
          </p>
          <p>
            The visual content generated by our AI based on your dream descriptions is owned by DreamBox, though we will always provide attribution to the dream contributor when possible.
          </p>

          <h2>6. User Rights</h2>
          <p>
            As a user, you have the right to:
          </p>
          <ul>
            <li>Request removal of content based on your dream description</li>
            <li>Request anonymization of your attribution</li>
            <li>Opt out of future dream collection</li>
          </ul>
          <p>
            To exercise these rights, please comment "please remove" on the relevant video or contact us directly.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>
            DreamBox provides its services "as is" without warranties of any kind. We are not liable for any damages arising from your use of our services or any content posted on our platforms.
          </p>
          <p>
            We do not guarantee that:
          </p>
          <ul>
            <li>Your dream will be selected for visualization</li>
            <li>The visual representation will exactly match your dream experience</li>
            <li>Our services will be uninterrupted or error-free</li>
          </ul>

          <h2>8. Modifications to Terms</h2>
          <p>
            We reserve the right to modify these Terms of Service at any time. We will notify users of significant changes by posting an update on our website. Your continued use of our services after such modifications constitutes your acceptance of the updated terms.
          </p>

          <h2>9. Termination</h2>
          <p>
            We reserve the right to terminate or suspend access to our services for any user who violates these Terms of Service or our Content Guidelines.
          </p>

          <h2>10. Governing Law</h2>
          <p>
            These Terms of Service are governed by and construed in accordance with the laws of the United States, without regard to its conflict of law principles.
          </p>

          <h2>11. Contact Information</h2>
          <p>
            If you have any questions about these Terms of Service, please contact us at:
          </p>
          <p>
            <a href="mailto:terms@dreambox.ai" className="text-indigo-400 hover:text-indigo-300">terms@dreambox.ai</a>
          </p>

          <p className="text-sm text-gray-400 mt-8">Last Updated: June 15, 2023</p>
        </div>
      </div>

      <div className="mt-8 text-center">
        <Link href="/" className="btn-secondary">
          Back to Home
        </Link>
      </div>
    </div>
  );
} 